"use client";

import { useEffect } from "react";
import { LogOut, ShoppingBasket } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

/* Account page — static island driven by /js/auth.js:
   /api/auth/me → profile card + verified chip + sign out, /api/auth/orders → order cards. */
export function AccountView() {
  useEffect(() => {
    if (!document.querySelector("script[data-auth-page]")) {
      const s = document.createElement("script");
      s.src = "/js/auth.js?v=20261005d"; s.async = true; s.dataset.authPage = "1";
      document.head.appendChild(s);
    }
  }, []);

  return (
    <div className="min-h-screen bg-white">
      <SiteHeader />
      <main className="pb-20">
        <section className="mx-auto max-w-xl px-4 pt-14 sm:pt-16">
          {/* signed out */}
          <div data-account-signedout className="rounded-[28px] bg-[#f5f5f7] p-10 text-center" hidden>
            <span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-white text-ink shadow-[0_2px_10px_rgba(0,0,0,0.06)]">
              <ShoppingBasket size={26} strokeWidth={1.8} />
            </span>
            <h1 className="mt-5 font-display text-[24px] font-extrabold tracking-tight text-ink">You&rsquo;re not signed in</h1>
            <p className="mx-auto mt-2 max-w-xs text-[14px] font-medium leading-relaxed text-muted-foreground">
              Sign in to see your orders and profile — or keep shopping, no account needed.
            </p>
            <div className="mt-6 flex flex-wrap justify-center gap-3">
              <a className="fresh-grad inline-flex h-11 items-center rounded-full px-7 text-[14px] font-bold text-white shadow-[0_8px_20px_rgba(11,124,49,0.35)] transition hover:brightness-[1.05] active:scale-[0.98]" href="/login">Sign in</a>
            </div>
          </div>

          {/* signed in */}
          <div data-account-view hidden>
            <div className="account-panel rounded-[28px] border border-line bg-white p-6 shadow-[0_2px_12px_rgba(0,0,0,0.04)] sm:p-7">
              <div className="flex items-center gap-4">
                <span className="account-avatar grid h-14 w-14 shrink-0 place-items-center rounded-full bg-mint text-[17px] font-extrabold text-leaf" data-account-avatar aria-hidden="true">R</span>
                <div className="min-w-0 flex-1">
                  <h1 className="truncate text-[21px] font-extrabold tracking-tight text-ink" data-account-name>…</h1>
                  <p className="mt-0.5 flex flex-wrap items-center gap-x-2 gap-y-1 text-[13px] font-medium text-muted-foreground" data-account-meta></p>
                </div>
                <button
                  className="inline-flex h-10 shrink-0 items-center gap-1.5 rounded-full border border-line-2 bg-white px-4 text-[13px] font-bold text-ink transition hover:bg-[#f5f5f7]"
                  type="button" data-logout
                >
                  <LogOut size={14} /> Sign out
                </button>
              </div>
            </div>

            <div className="mt-9">
              <h2 className="text-[11px] font-bold uppercase tracking-[0.14em] text-muted-foreground">History</h2>
              <h3 className="mt-2 font-display text-[21px] font-extrabold tracking-tight text-ink">Your orders</h3>
              <div data-orders-list className="mt-5"></div>
              <div data-orders-empty className="empty-state rounded-[28px] bg-[#f5f5f7] p-10 text-center" hidden>
                <span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-white text-ink shadow-[0_2px_10px_rgba(0,0,0,0.06)]">
                  <ShoppingBasket size={22} strokeWidth={1.8} />
                </span>
                <h4 className="mt-4 text-[15px] font-bold text-ink">No orders yet</h4>
                <p className="mt-1.5 text-[13px] font-medium text-muted-foreground">Your first Rebesta order will appear here.</p>
                <a className="carrot-grad mt-5 inline-flex h-11 items-center rounded-full px-7 text-[14px] font-bold text-white shadow-[0_8px_20px_rgba(232,71,12,0.35)] transition hover:brightness-[1.05]" href="/shop">Start shopping</a>
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* styles for DOM generated by auth.js (verified chip, order cards) */}
      <style>{`
        .verified-chip { display:inline-flex; align-items:center; gap:4px; border-radius:9999px; background:#f0f5f0;
          color:#0d8736; padding:2px 8px 2px 6px; font-size:0.68rem; font-weight:700; }
        .verified-chip svg { width:11px; height:11px; }
        .account-order { display:flex; align-items:center; justify-content:space-between; gap:12px; flex-wrap:wrap;
          background:#fff; border:1px solid #e8e8ed; border-radius:18px; padding:16px 18px; margin-bottom:10px;
          text-decoration:none; transition:box-shadow .18s, transform .18s; }
        .account-order:hover { box-shadow:0 8px 24px rgba(0,0,0,0.08); transform:translateY(-1px); }
        .ao-main strong { display:block; font-size:0.95rem; font-weight:700; color:#1d1d1f; }
        .ao-main span { font-size:0.78rem; font-weight:500; color:#4a4a4f; }
        .ao-side { display:flex; align-items:center; gap:10px; }
        .ao-id { font-size:0.72rem; font-weight:600; color:#4a4a4f; font-variant-numeric:tabular-nums; }
        .badge { display:inline-flex; align-items:center; border-radius:9999px; padding:3px 10px; font-size:0.66rem; font-weight:700; }
        .badge.green { background:#f0f5f0; color:#0d8736; }
        .badge.orange { background:rgba(255,91,32,0.10); color:#d84a15; }
        .badge.gray { background:rgba(0,0,0,0.06); color:#4a4a4f; }
        .account-order.in { animation:orderIn .35s ease; }
        @keyframes orderIn { from { opacity:0; transform:translateY(8px); } to { opacity:1; transform:none; } }
      `}</style>
      <SiteFooter />
    </div>
  );
}
